### ISSUE TITLE
Tracking issue for std::future migration

### ISSUE THREAD

**Issue by semtexzv** [actix/actix-net#45]
This issue tracks the migration.

Crates migrated:

- [x] - actix-threadpool #46 
- [x] - actix-rt  #47 
- [x] - actix-codec #48 
- [x]  - actix-service (discussion needed) #57  
- [x]  - actix-server-config (Needs bugfixing)
- [x]  - actix-server (Needs bugfixing)
- [x]  - actix-utils
- [x]  - actix-connect
- [x]  - actix-ioframe

note: these are in rough dependency order

Decisions:

1. The old future trait had `Item`, and `Error` associated types. This meant it was similar to the Result type, and thus, every function that returned future was fallible. Now, the future has only one associated type, that denotes infallible future output.

    Several places return a future with a result, that is not used anywhere, or its error type is `()`. Which of these occurences should be replaced with `Future<Output=Item>`, and which with `Future<Output=Result<Item,Error>>`?

2.  Usage of the `Pin<&mut Self>` in places similar to future, this means the `Service::poll_ready` and `ActorFuture::poll` in actix. 

    There is a reason for using these Pins in the poll method, should we upgrade our definitions of 
traits similar to `Future` to also utilize them ?. Also, maybe not, since these were primarily introduced to support await in the form of generators. Need more info from qualified people.

3. Usage and form of macros / functions to ease pinning and unpinning. 
    
    I am currently working on actix-service, and it is a massive chore to always create unsafe block in 
order to create or destrucure a `Pin<&mut T>`. This can be sometimes solved by pin projections from the `pin-utils` crate, but it does not allow splitting borrows ( Creating multiple pins to multiple fields of a struct), which is a massive pain.

**Comment by fafhrd91** [comment]
Lets crate Pr per crate. Do you want to do dev actix-net repo?

**Comment by fafhrd91** [comment]
We can also skip actix-tower, I’d like to remove it

**Comment by Jonathas-Conceicao** [comment]
I have played a little around moving some of the crates here to 0.3, I don't have anything final but I would also like to help.

About your points here's my opinion:
>1. Which of these occurences should be replaced with Future<Output=Item>, and which with Future<Output=Result<Item,Error>>?

Values that return the same time should not use a `Result`. But for values that does need a `Result` return type I think it's worth using the [TryFuture](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.18/futures/future/trait.TryFuture.html) trait.

>2. Should we upgrade our definitions of traits similar to Future to also utilize them (Pin<&mut Self>) ?

I don't think it's necessary, at least not from what I've seen so far.

>3. Usage and form of macros / functions to ease pinning and unpinning.

I have seen this being necessary when porting the actix-service crate, and [pin-project](https://github.com/taiki-e/pin-project) may be an handy alternative too.

**Comment by semtexzv** [comment]
1. I don't think we should pollute the codebase with TryFuture.  On the other hand, it could simplify the migration ( I'll do some experiments on actix-service with TryFuture, because when I tried it with Future, I got bogged down in rewriting generic bounds pretty quickly).

As to the second issue, I think we should utilize this guarantee, At least for `Service`, `ActorFuture` and `ActorStream`, since these types store unboxed futures internally and can be polled repeatedly.
We should utilize guarantees provided by Pin in order ensure inner futures are never moved too.

3. Thanks, I checked out the pin-project and will probably use it.

**Comment by cdbattags** [comment]
Hi folks! Wanted to get my feet wet in actix with the work needed here.

Maybe jump into the bugfixes for actix-server?

Also, any better testing flow than plain ol' `cargo test`?

**Comment by cdbattags** [comment]
Can we give @semtexzv access to this repo so we can get all his PRs/changes into the `std-future` branch? That way I don't have to track these all separately as I continue to work on converting.

**Comment by JohnTitor** [comment]
@cdbattags They already have access to do so.

**Comment by cdbattags** [comment]
@JohnTitor yep, saw your comment on the first draft PR

**Comment by semtexzv** [comment]
I don't have any time whatsoever atm, But check the work on my fork (https://github.com/semtexzv/actix-net). Everything up to actix-server is done in separate branches and kinda works.

All you need to do is to update the versions, fix any inconsistencies, and most of the tests should work.

This code is not production ready. Most of the migrations were performed naively, not trying to update the code to utilize new features.

**Comment by cdbattags** [comment]
@fafhrd91 Looked through your work today. Where shall we go from here on the `std-future` branch? I know we still have a long way to go on `actix-service`. I'm free all day tomorrow to collab.

**Comment by fafhrd91** [comment]
it is done

**Comment by rofrol** [comment]
@fafhrd91 Great. Can we use async/await now? Are there any some examples?

**Comment by fafhrd91** [comment]
you can in actix-net

**Comment by fafhrd91** [comment]
https://github.com/actix/actix-net/blob/7ba05135791e7ded295c8fef72e5cbce854c103f/actix-server/tests/test_server.rs#L111

**Comment by rofrol** [comment]
And what is the plan for https://github.com/actix/examples? Migrate to `async/await` or is it not possible yet?

**Comment by 0xpr03** [comment]
As most of these are actix-web 1.0 I'd wait till actix-web 2.0 with async/await is there. (or rather: you probably need actix-web 2.0 API stability before you can port them ? )

**Comment by robjtede** [comment]
I’d imagine the best approach would be have examples for both and separate them v1/v2 until the futures 0.1 ecosystem is less commonplace.
